component: http
name: http-egg-0vY46Bo7z
inputs:
  src:
    src: ./
    exclude:
      - .env
  faas:
    framework: egg
    name: '${name}'
    runtime: Nodejs12.16
    eip: false
    timeout: 3
    memorySize: 512
    tags: []
    environments: []
    layers:
      - name: '${output:${stage}:${app}:xnj-egg-serverless-layer.name}'
        version: '${output:${stage}:${app}:xnj-egg-serverless-layer.version}'
  apigw:
    protocols:
      - http
      - https
    timeout: 60
    environment: release
    customDomains: []
  region: ap-shanghai
  isAutoCiDeploy: false
org: '1308124158'
app: xnj-egg-serverless
stage: dev
